tictactoe/config/routes.rb
Tictactoe::Application.routes.draw do

  resources :games do
    :moves
  end

  resources :users

end

tictactoe/app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :game_complete, :game_title, :player_1, :player_2, :user_id

  belongs_to :user
  has_many :moves
  
end

tictactoe/app/models/move.rb
class Move < ActiveRecord::Base
  attr_accessible :cell, :game_id, :move_number, :user

belongs_to :game

end

tictactoe/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :games_lost, :games_won, :password, :username

has_many :moves, through: :games
has_many :games

end

tictactoe/app/controllers/games_controller.rb
class GamesController < ApplicationController

  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

tictactoe/app/controllers/moves_controller.rb
class MovesController < ApplicationController
  protect_from_forgery
end

tictactoe/app/controllers/users_controller.rb
class UsersController < ApplicationController

# GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

tictactoe/app/helpers/games_helper.rb
module GamesHelper
end

tictactoe/app/helpers/layout_helper.rb
module UsersHelper
end

tictactoe/app/helpers/moves_helper.rb
module MovesHelper
end

tictactoe/app/helpers/users_helper.rb
module UsersHelper
end

tictactoe/app/views/games/_form.html.erb
<%= form_for @games do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

tictactoe/app/views/games/edit.html.erb
<% title "Edit Game" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @game %> |
  <%= link_to "View All", games_path %>
</p>

tictactoe/app/views/games/index.html.erb
<% title "Games" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for game in @games %>
    <tr>
      <td><%= game.name %></td>
      <td><%= link_to "Show", game %></td>
      <td><%= link_to "Edit", edit_game_path(game) %></td>
      <td><%= link_to "Destroy", game, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Game", new_game_path %></p>

tictactoe/app/views/games/new.html.erb
<% title "New Game" %>

<%= render 'form' %>

<p><%= link_to "Back to List", games_path %></p>

tictactoe/app/views/games/show.html.erb
<% title "Game" %>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <%= link_to "Edit", edit_game_path(@game) %> |
  <%= link_to "Destroy", @game, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", games_path %>
</p>

tictactoe/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tictactoe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

tictactoe/app/views/moves/_form.html.erb
<%= form_for @moves do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

tictactoe/app/views/moves/edit.html.erb
<% title "Edit Move" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @move %> |
  <%= link_to "View All", moves_path %>
</p>

tictactoe/app/views/moves/index.html.erb
<% title "Moves" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for move in @moves %>
    <tr>
      <td><%= move.name %></td>
      <td><%= link_to "Show", move %></td>
      <td><%= link_to "Edit", edit_move_path(move) %></td>
      <td><%= link_to "Destroy", move, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Move", new_move_path %></p>

tictactoe/app/views/moves/new.html.erb
<% title "New Move" %>

<%= render 'form' %>

<p><%= link_to "Back to List", moves_path %></p>

tictactoe/app/views/moves/show.html.erb
show.html.erb<% title "Move" %>

<p>
  <strong>Name:</strong>
  <%= @move.name %>
</p>

<p>
  <%= link_to "Edit", edit_move_path(@move) %> |
  <%= link_to "Destroy", @move, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", moves_path %>
</p>

tictactoe/app/views/users/_form.html.erb
<%= form_for @users do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

tictactoe/app/views/users/edit.html.erb
<% title "Edit User" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @user %> |
  <%= link_to "View All", users_path %>
</p>

tictactoe/app/views/users/index.html.erb
<% title "Users" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.name %></td>
      <td><%= link_to "Show", user %></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
      <td><%= link_to "Destroy", user, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New User", new_user_path %></p>

tictactoe/app/views/users/new.html.erb
<% title "New User" %>

<%= render 'form' %>

<p><%= link_to "Back to List", users_path %></p>

tictactoe/app/views/users/show.html.erb
show.html.erb<% title "User" %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <%= link_to "Edit", edit_user_path(@user) %> |
  <%= link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", users_path %>
</p>