haml_koala_tictactoe2/tictactoe_2/config/routes.rb
Tictactoe2::Application.routes.draw do
  resources :sessions
get "/logout", to: "sessions#destroy"
  

  resources :games do 
    resources :moves 
  end

  resources :users

  root :to => 'users#index'
  

end

haml_koala_tictactoe2/tictactoe_2/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tictactoe2
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    / <div class="wrapper">
    - flash.each do |name, msg|
      %div{:class => "flash-message flash-message-#{name}"}
        = msg
    %header
      %nav
        %ul
          - if current_user
            %li
              hello #{current_user.email}
            %li= link_to "log out", logout_path
          - else
            %li= link_to "log in", new_session_path
            %li= link_to "sign up", new_user_path
    - if current_user && current_user.role == "admin"
      You're the boss ! you have access to all the secrets
    - elsif current_user && current_user.role == "user"
      You can't access everything because you're a simple user
    %nav
      #Button
      = link_to image_tag('ouser_button_allblack.png'), users_path
      %br/
      %br/
      / <input type="image" src="derp.png" onMouseOver="this.src='aderp.png'" onMouseOut="this.src='derp.png'">
      #Button2
      = link_to image_tag('xgame_button_allblack.png'), games_path
    = yield

/ *************************************************
/ <!DOCTYPE html>
/ <html>
/ <head>
/   <title>Tictactoe2</title>
/   <%#= stylesheet_link_tag    "application", :media => "all" %>
/   <%#= javascript_include_tag "application" %>
/   <%#= csrf_meta_tags %>
/ </head>
/ <body>
/ <!--   <div class="wrapper"> -->

/       <%# flash.each do |name, msg| %>
/         <!-- <div class="flash-message flash-message-<%#= name %>"> -->
/           <%#= msg %>
/         <!-- </div> -->
/ <!-- #       <%# end %>
/ #     <header>
/ #       <nav> -->
/ # <!--         <ul>
/ #           <%# if current_user %>
/ #           <li>hello <%#= current_user.email %></li>
/ #           <li><%#= link_to "log out", logout_path %></li>
/ #           <%#else%>
/ #           <li><%#= link_to "log in", new_session_path %></li>
/ #           <li><%#= link_to "sign up", new_user_path %></li>
/ #           <%# end %>
/ #         </ul>
/ #       </nav>
/ #     </header> -->

/ <!-- 
/ #     <%# if current_user && current_user.role == "admin" %>
/ #         You're the boss ! you have access to all the secrets
/ #       <%# elsif current_user && current_user.role == "user" %>
/ #         You can't access everything because you're a simple user 
/ #       <%# end %> -->

/ # <!--       <nav>
/ #         <div id="Button"></div>
/ #         <%#=link_to image_tag('ouser_button_allblack.png'), users_path %>
/ #         </div>
/ #         <br>
/ #         <br> -->
/ #     <!--     <input type="image" src="derp.png" onMouseOver="this.src='aderp.png'" onMouseOut="this.src='derp.png'"> -->
/ #       <!-- <div id="Button2"></div>
/ #         <%#=link_to image_tag('xgame_button_allblack.png'), games_path %></div> -->
/ <!-- #         <%#=link_to 'moves', moves_path %>
/ #     </nav>

/ #     <%#= yield %> -->
/ # <!--   </div> -->
/ <!-- # </body>
/ # </html> --> -->