haml_koala_tictactoe2/tictactoe_2/config/routes.rb
Tictactoe2::Application.routes.draw do
  resources :sessions
get "/logout", to: "sessions#destroy"
  

  resources :games do 
    resources :moves 
  end

  resources :users

  root :to => 'users#index'
  

end

haml_koala_tictactoe2/tictactoe_2/app/models/game.rb
class Game < ActiveRecord::Base
    attr_accessible :game_complete, :game_title, :player_1, :player_2, :user_id

    # belongs_to :player_1, class_name: 'User'
    # belongs_to :player_2, class_name: 'User'

    has_many :moves


  WINNING_MOVES = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [6, 4, 8], [6, 4, 2]]



  def build_board
    @board = [nil, nil, nil, nil, nil, nil, nil, nil, nil]
    self.moves.each do |move|
      @board[move.cell] = move.symbol
    end
    @board
  end


  #.any? iterates through each SINGLE value (so ignores that values are in arrays)
  def check_win?
    @board = build_board
    result = WINNING_MOVES.any? do |winning_solution| 
      result1 = winning_solution[0]
      result2 = winning_solution[1]
      result3 = winning_solution[2]

      @board[result1] != nil && @board[result1] == @board[result2] && @board[result2] == @board[result3]
    end

  end


end

haml_koala_tictactoe2/tictactoe_2/app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    @board = @game.build_board

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])
    @game.player_1 = current_user.id
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

haml_koala_tictactoe2/tictactoe_2/app/helpers/games_helper.rb
module GamesHelper
end

haml_koala_tictactoe2/tictactoe_2/app/views/games/_form.html.haml
= form_for(@game) do |f|
  - if @game.errors.any?
    #error_explanation
      %h2
        = pluralize(@game.errors.count, "error")
        prohibited this game from being saved:
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :game_title
    %br/
    = f.text_field :game_title
  .field
    = f.label :player_2
    %br/
    = f.collection_select(:player_2, User.all, :id, :email)
  .actions
    = f.submit

/ *********************************
/ # <%= form_for(@game) do |f| %>
/ #   <% if @game.errors.any? %>
/ #     <div id="error_explanation">
/ #       <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

/ #       <ul>
/ #       <% @game.errors.full_messages.each do |msg| %>
/ #         <li><%= msg %></li>
/ #       <% end %>
/ #       </ul>
/ #     </div>
/ #   <% end %>




/ #   <div class="field">
/ #     <%= f.label :game_title %><br />
/ #     <%= f.text_field :game_title %>
/ #   </div>
/ #   <div class="field">
/ #     <%= f.label :player_2 %><br />
/ #     <%= f.collection_select(:player_2, User.all, :id, :email) %>
/ #   </div>
  
/ #   <div class="actions">
/ #     <%= f.submit %>
/ #   </div>
/ # <% end %>

haml_koala_tictactoe2/tictactoe_2/app/views/games/edit.html.haml
%h1 Editing game
= render 'form'
= link_to 'Show', @game
|
\#{link_to 'Back', games_path}


/ <h1>Editing game</h1>

/ <%= render 'form' %>

/ <%= link_to 'Show', @game %> |
/ <%= link_to 'Back', games_path %>

haml_koala_tictactoe2/tictactoe_2/app/views/games/index.html.haml
%h1 GAME HISTORY
%table
  %tr
    %th User
    %th Game title
    %th Player 1
    %th Player 2
    %th Game complete
    %th
    %th
    %th
  - @games.each do |game|
    %tr
      %td= game.game_title
      %td= game.player_1
      %td= game.player_2
      %td= game.game_complete
      %td= link_to 'Show', game
      %td= link_to 'Edit', edit_game_path(game)
      %td= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Game', new_game_path


/ ******************************************


/ <h1>GAME HISTORY</h1>

/ <table>
/   <tr>
/     <th>User</th>
/     <th>Game title</th>
/     <th>Player 1</th>
/     <th>Player 2</th>
/     <th>Game complete</th>
/     <th></th>
/     <th></th>
/     <th></th>
/   </tr>

/ <% @games.each do |game| %>
/   <tr>
/     <td><%= game.game_title %></td>
/     <td><%= game.player_1 %></td>
/     <td><%= game.player_2 %></td>
/     <td><%= game.game_complete %></td>
/     <td><%= link_to 'Show', game %></td>
/     <td><%= link_to 'Edit', edit_game_path(game) %></td>
/     <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
/   </tr>
/ <% end %>
/ </table>
/ <br />



/ <%= link_to 'New Game', new_game_path %>

haml_koala_tictactoe2/tictactoe_2/app/views/games/new.html.haml
%h1 New game
= render 'form'
= link_to 'Back', games_path

/ *****************************

/ <!-- <h1>New game</h1>

/ <%#= render 'form' %>

/ <%#= link_to 'Back', games_path %> -->

haml_koala_tictactoe2/tictactoe_2/app/views/games/show.html.haml
%br/
%h1 PLAY!
%p#notice= notice
/
  <p>
  <b>User:</b>
  <haml_silent>
  </haml_silent></p>
%p
  %b Game title:
  = @game.game_title
%p
  %b Player 1:
  = @game.player_1
%p
  %b Player 2:
  = @game.player_2
/
  <p>
  <b>Player<haml_loud> @player_1 </haml_loud>, it's your turn</b>
  </p>
/
  <p>
  <b>Game complete:</b>
  <haml_loud> @game.game_complete </haml_loud>
  </p>
/ DISPLAY WINNER
%h2
  - if @game.check_win?
    = "WINNER!"
.boxes
  - @board.each_with_index do |move, square_id|
    - if move == 'X'
      = image_tag('X_symbol.png', class: 'square')
      / *define class for css
    - elsif move == 'O'
      = image_tag('O_symbol_black.png', class: 'square')
    - else
      = link_to " ", new_game_move_path(@game, square_id: square_id),  class: 'square'
.back
  = link_to 'Edit', edit_game_path(@game)
  |
  \#{link_to 'Back', games_path}


/ *******************************************

/ <br>

/ <h1>PLAY!</h1>

/ <p id="notice"><%= notice %></p>

/ <!-- <p>
/   <b>User:</b>
/   <%#= @game.user_id %>
/ </p> -->

/ <p>
/   <b>Game title:</b>
/   <%= @game.game_title %>
/ </p>

/ <p>
/   <b>Player 1:</b>
/   <%= @game.player_1 %>
/ </p>

/ <p>
/   <b>Player 2:</b>
/   <%= @game.player_2 %>
/ </p>

/ <!-- <p>
/   <b>Player<%= @player_1 %>, it's your turn</b>
/ </p> -->

/ <!-- <p>
/   <b>Game complete:</b>
/   <%= @game.game_complete %>
/ </p> -->


/ <!-- DISPLAY WINNER -->
/ <h2><%if @game.check_win?%>
/   <%="WINNER!"%></td>
/ <%end%></h2>

/ <div class='boxes'>
/   <% @board.each_with_index do |move, square_id| %>
/   <% if move == 'X' %>
/     <%= image_tag('X_symbol.png', class: 'square') %>
/    <!--  *define class for css -->
/     <% elsif move == 'O'%>
/       <%= image_tag('O_symbol_black.png', class: 'square') %>
/       <% else %>
/           <%= link_to " ", new_game_move_path(@game, square_id: square_id),  class: 'square'%>
/     <% end %>
/   <% end %>
/ </div>

/ <div class="back">
/   <%= link_to 'Edit', edit_game_path(@game) %> |
/   <%= link_to 'Back', games_path %>
/ </div>