haml_koala_tictactoe2/tictactoe_2/config/routes.rb
Tictactoe2::Application.routes.draw do
  resources :sessions
get "/logout", to: "sessions#destroy"
  

  resources :games do 
    resources :moves 
  end

  resources :users

  root :to => 'users#index'
  

end

haml_koala_tictactoe2/tictactoe_2/app/models/move.rb
class Move < ActiveRecord::Base
  attr_accessible :game_id, :symbol, :user_id, :cell

  belongs_to :game

end

haml_koala_tictactoe2/tictactoe_2/app/controllers/moves_controller.rb
class MovesController < ApplicationController
  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @moves }
    end
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
    @move = Move.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @move }
    end
  end


  # ASSIGNING X AND O TO PLAYERS
  def new
    @game = Game.find(params[:game_id])
    if current_user.id == @game.player_1
      player_symbol = 'X'
    else
      player_symbol = 'O'
    end
    
  # ADDING THE MOVE AND IT'S VARIABLES TO THE DATABASE 
  @game.moves.create(cell: params[:square_id], user_id: current_user.id, symbol: player_symbol)
  # REDIRECTS TO THE SHOW PAGE
  redirect_to game_path(@game)
end

  # GET /moves/1/edit
  def edit
    @move = Move.find(params[:id])
  end

  def create
  end

  # PUT /moves/1
  # PUT /moves/1.json
  def update
    @move = Move.find(params[:id])

    respond_to do |format|
      if @move.update_attributes(params[:move])
        format.html { redirect_to @move, notice: 'Move was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move = Move.find(params[:id])
    @move.destroy

    respond_to do |format|
      format.html { redirect_to moves_url }
      format.json { head :no_content }
    end
  end
end

haml_koala_tictactoe2/tictactoe_2/app/helpers/moves_helper.rb
module MovesHelper
end

haml_koala_tictactoe2/tictactoe_2/app/views/moves/_form.html.haml
= form_for(@move) do |f|
  - if @move.errors.any?
    #error_explanation
      %h2
        = pluralize(@move.errors.count, "error")
        prohibited this move from being saved:
      %ul
        - @move.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :user_id
    %br/
    = f.text_field :user_id
  .field
    = f.label :symbol
    %br/
    = f.text_field :symbol
  .field
    = f.label :game_id
    %br/
    = f.text_field :game_id
  .actions
    = f.submit

/ *******************************
/ <%= form_for(@move) do |f| %>
/   <% if @move.errors.any? %>
/     <div id="error_explanation">
/       <h2><%= pluralize(@move.errors.count, "error") %> prohibited this move from being saved:</h2>

/       <ul>
/       <% @move.errors.full_messages.each do |msg| %>
/         <li><%= msg %></li>
/       <% end %>
/       </ul>
/     </div>
/   <% end %>

/   <div class="field">
/     <%= f.label :user_id %><br />
/     <%= f.text_field :user_id %>
/   </div>
/   <div class="field">
/     <%= f.label :symbol %><br />
/     <%= f.text_field :symbol %>
/   </div>
/   <div class="field">
/     <%= f.label :game_id %><br />
/     <%= f.text_field :game_id %>
/   </div>
/   <div class="actions">
/     <%= f.submit %>
/   </div>
/ <% end %>

haml_koala_tictactoe2/tictactoe_2/app/views/moves/edit.html.haml
%h1 Editing move
= render 'form'
= link_to 'Show', @move
|
\#{link_to 'Back', moves_path}


/ **************************
/ <h1>Editing move</h1>

/ <%= render 'form' %>

/ <%= link_to 'Show', @move %> |
/ <%= link_to 'Back', moves_path %>

haml_koala_tictactoe2/tictactoe_2/app/views/moves/index.html.haml
%h1 Listing moves
%table
  %tr
    %th User
    %th Symbol
    %th Game
    %th
    %th
    %th
  - @moves.each do |move|
    %tr
      %td= move.user_id
      %td= move.symbol
      %td= move.game_id
      %td= link_to 'Show', move
      %td= link_to 'Edit', edit_move_path(move)
      %td= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Move', new_move_path

/ ***********************

/ <h1>Listing moves</h1>

/ <table>
/   <tr>
/     <th>User</th>
/     <th>Symbol</th>
/     <th>Game</th>
/     <th></th>
/     <th></th>
/     <th></th>
/   </tr>

/ <% @moves.each do |move| %>
/   <tr>
/     <td><%= move.user_id %></td>
/     <td><%= move.symbol %></td>
/     <td><%= move.game_id %></td>
/     <td><%= link_to 'Show', move %></td>
/     <td><%= link_to 'Edit', edit_move_path(move) %></td>
/     <td><%= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
/   </tr>
/ <% end %>
/ </table>

/ <br />

/ <%= link_to 'New Move', new_move_path %>

haml_koala_tictactoe2/tictactoe_2/app/views/moves/new.html.haml
%h1 New move
= render 'form'

/ *******************
/ <h1>New move</h1>

/ <%= render 'form' %>

/ <%#= link_to 'Back', moves_path %>

haml_koala_tictactoe2/tictactoe_2/app/views/moves/show.html.haml
%p#notice= notice
%p
  %b User:
  = @move.user_id
%p
  %b Symbol:
  = @move.symbol
%p
  %b Game:
  = @move.game_id
= link_to 'Edit', edit_move_path(@move)
|
\#{link_to 'Back', moves_path}

/ ************************************
/ <p id="notice"><%= notice %></p>

/ <p>
/   <b>User:</b>
/   <%= @move.user_id %>
/ </p>

/ <p>
/   <b>Symbol:</b>
/   <%= @move.symbol %>
/ </p>

/ <p>
/   <b>Game:</b>
/   <%= @move.game_id %>
/ </p>


/ <%= link_to 'Edit', edit_move_path(@move) %> |
/ <%= link_to 'Back', moves_path %>